### ISSUE TITLE
Progress and animate out not working for newest files.

### ISSUE THREAD

**Issue by meltynetv2** [Mobius1/bulletin#2]
Hello, not sure how no one else is experiencing this issue, but I've done some researching and found that only the v1.1.6 version has working progress bars for simple notifications, advanced notifications seem to always have progress bars. So after downgrading to 1.1.6 they now have progress bars, but 1.1.7+ don't. Whatever was changed from 1.1.6 to 1.1.7 that broke the progress bars ever showing on simple notifications. 

As well I have tried everything I believe and the animation out does not work on any of these version stated above, the notification always just disappear instead of fading out(fadeOut). I have experience with animation.css, it always works for other projects, but I'm not sure why it doesn't work for my bulletin. 

If you can spread some light on how to fix these exit animation it would be appreciated as the progress bars are fixed with the 1.1.6 version.

*FYI I did not change the call for the simple notifications when testing, just the app.js file for bulletin and it worked after finding the correct version.*

**Comment by Mobius1** [comment]
I'll take a look today to see what's going on.

**Comment by Mobius1** [comment]
I've found the bug breaking the progress bars and fixed it in [v1.1.9](https://github.com/Mobius1/bulletin/releases/tag/1.1.9).

Exit animations were fixed in `v1.1.8`.

**Comment by meltynetv2** [comment]
> I've found the bug breaking the progress bars and fixed it in [v1.1.9](https://github.com/Mobius1/bulletin/releases/tag/1.1.9).
> 
> Exit animations were fixed in `v1.1.8`.

Thank you! Appreciate the fast effort and I'm glad this has been fixed. I will report back momentarily with my findings.

**Comment by meltynetv2** [comment]
> I've found the bug breaking the progress bars and fixed it in [v1.1.9](https://github.com/Mobius1/bulletin/releases/tag/1.1.9).
> 
> Exit animations were fixed in `v1.1.8`.

Hello, I have tried the new 1.1.9 version and the progressbars are now working on the simple notifications. Although I am still having an issue with the exit animations... I have tried setting the exitAnim property and not setting it and no luck.

Here is my code for executing a notification:
`exports['bulletin']:Send({
    	message = msg,
    	progress = true,
    	exitAnim = "fadeOut"
	})`

I am on version 1.1.9 and this code above does not show a notification with exit animation. Can you look into this and let me know if you find out what is causing this? Much appreciated and keep up the great work!

**Comment by Mobius1** [comment]
Very strange. I've tested with the code below and exit animations are working my end.

```lua
Citizen.CreateThread(function()
    local exits = { 'fadeOut', 'fadeOutLeft', 'flipOutX', 'flipOutY', 'bounceOutLeft', 'backOutLeft', 'slideOutLeft', 'zoomOut', 'zoomOutLeft' }

    Citizen.Wait(1000)

    for _, exit in ipairs(exits) do
        exports['bulletin']:Send({ message = exit, progress = true, exitAnim = exit, position = 'topleft' })

        Citizen.Wait(750)
    end
end)
```
[Result](https://streamable.com/48fg54)

**Comment by meltynetv2** [comment]
Alright, let me try this out. Is strange it doesn't work on my end specifically.

**Comment by meltynetv2** [comment]
> Very strange. I've tested with the code below and exit animations are working my end.
> 
> ```lua
> Citizen.CreateThread(function()
>     local exits = { 'fadeOut', 'fadeOutLeft', 'flipOutX', 'flipOutY', 'bounceOutLeft', 'backOutLeft', 'slideOutLeft', 'zoomOut', 'zoomOutLeft' }
> 
>     Citizen.Wait(1000)
> 
>     for _, exit in ipairs(exits) do
>         exports['bulletin']:Send({ message = exit, progress = true, exitAnim = exit, position = 'topleft' })
> 
>         Citizen.Wait(750)
>     end
> end)
> ```
> 
> [Result](https://streamable.com/48fg54)

So after testing this code, the only animations that worked was the "bounceOutLeft" and "backOutLeft". That one showed an animation for it's exit. Otherwise the rest didn't work. Possibly you can look and see if there is a difference between the code for the rest and the one that worked?

**Comment by meltynetv2** [comment]
@Mobius1 Hey! Did you by chance look into this and find any reason for this not working on my end or others? If not, should I just look into this myself? if not, I am completely fine using the 2 animations that do work for now. Appreciate the help given!

**Comment by Mobius1** [comment]
I've just moved my FiveM server onto a dedicated server and I'm now getting the same bugs you've reported. I need to look into what's going on.

**Comment by Mobius1** [comment]
For whatever reason, this repo had the wrong `animate.min.css` file included which was causing the exit animation bug. Fixed in `v1.1.10`.

**Comment by meltynetv2** [comment]
> For whatever reason, this repo had the wrong `animate.min.css` file included which was causing the exit animation bug. Fixed in `v1.1.10`.

Awesome! Appreciate the effort put in to fix this bug. Good work.
